### ISSUE TITLE
ErrorException Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by domainregistrar** [metaregistrar/rdap-client#14]
It seems Rdap.php line 120 uses deprecated PHP:

`                        if ($service[1][0]{strlen($service[1][0]) - 1} !== '/') {`

**Comment by metaregistrar** [comment]
The deprecated function has been fixed by replacing the curly braces with brackets.

**Comment by jesscostello** [comment]
It seems this deprecated functionality is also still being used on line 131 and line 143
