### ISSUE TITLE
How can Domains in country TLDs be found?

### ISSUE THREAD

**Issue by patlecat** [metaregistrar/rdap-client#9]
Hi and thanks for this lib! <3

Country TLDs like DE and CH domains can't be found currently with your lib, why is that? The RDAP should relay us to the correct NIC, right?

Swiss TLD: https://www.nic.ch/de/whois/rdap/

**Comment by metaregistrar** [comment]
RDAP is (like DNS) structured as a tree, with the root for domains starting at https://data.iana.org/rdap/dns.json

When DE and CH are not yet in that root, then everything under that extension cannot be found.

So the registries of DE and CH must update their RDAP info at ICANN, and then they will be found.

**Comment by patlecat** [comment]
So what do you suggest? That we add the rdap-nic ourselves when we parse an URL that we know isn't in the iana list? Like adding rdap.nic.ch/ for CH?

**Comment by metaregistrar** [comment]
You could do that - and you can e-mail the people of nic.ch to ask when their RDAP service is going to be added to the rdap root.

**Comment by patlecat** [comment]
@metaregistrar Yeah ok but where to add it exactly? Could you please add an interface to add other rdap-servers where needed in your lib? And please also add comments to show what you are doing and why.

**Comment by metaregistrar** [comment]
Root servers are read in the function readRoot() in rdap.php.

Created a new function $rdap->addTld('ch','https://rdap.nic.ch');

For the time some rdap services are not in the root yet, you can add them there.

**Comment by patlecat** [comment]
Awesome, thanks man.
